/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      maxWidth: {
        'screen-2xl': '1600px', 
        'custom-1200': '1200px', 
        'custom-900': '900px', 
      },
      colors: {
        'primary': '#0040e0',
        'primary-container': '#2e5bff',
        'on-primary': '#ffffff',
        'primary-fixed': '#dde1ff',
        'on-primary-fixed': '#001356',
        'on-primary-fixed-variant': '#0035be',
        'secondary-fixed-dim': '#bcc7de',
        'surface-bright': '#f7f9fb',
        'secondary-fixed': '#d8e3fb',
        'on-error': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-container': '#ffede6',
        'tertiary-fixed': '#ffdbcd',
        'on-background': '#191c1e',
        'primary-fixed-dim': '#b8c3ff',
        'inverse-surface': '#2d3133',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed': '#111c2d',
        'on-surface-variant': '#434655',
        'surface-container': '#eceef0',
        'error-container': '#ffdad6',
        'on-primary-container': '#efefff',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#b8c3ff',
        'on-secondary': '#ffffff',
        'error': '#ba1a1a',
        'tertiary-container': '#bc4800',
        'on-secondary-container': '#586377',
        'on-secondary-fixed-variant': '#3c475a',
        'surface-dim': '#d8dadc',
        'outline': '#737686',
        'surface-container-high': '#e6e8ea',
        'surface-container-low': '#f2f4f6',
        'on-tertiary-fixed': '#360f00',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#ffb596',
        'secondary': '#545f73',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-surface': '#191c1e',
        'background': '#f7f9fb',
        'tertiary': '#943700',
        'surface-tint': '#124af0',
        'secondary-container': '#d5e0f8',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c3c6d7',
        'surface': '#f7f9fb',
        'primary-legacy': '#ed3849',
        'primary-dark': "#d23141",
        'primary-light': '#f4e5ec',
        'text-dark': '#0f172a',
        'text-light': '#64748b',
        'extra-light': '#f8fafc'
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
      },
      
      keyframes:{
        fadeUp:{
          '0%': { opacity: 0, transform: 'translateY(20px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        zoomIn:{
          '0%': { opacity: 0, transform: 'scale(0.8)' },
          '100%': { opacity: 1, transform: 'scale(1)' },
        },
        slideLeft:{
          '0%': { opacity: 0, transform: 'translateX(-40px)' },
          '100%': { opacity: 1, transform: 'translateX(0)' },
        },
        shrimmer:{
          '0%': { backgroundPosition: '200% center' },
        '100%': { backgroundPosition: '-200% center' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        blob2: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(-50px, 30px) scale(1.1)' },
          '66%': { transform: 'translate(20px, -20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        blob3: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(20px, 20px) scale(1.1)' },
          '66%': { transform: 'translate(-30px, -30px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
      },
      animation:{
        fadeUp: 'fadeUp 0.8s ease-out forwards',
        zoomIn: 'zoomIn 0.6s ease-out forwards',
        slideLeft: 'slideLeft 0.6s ease-out forwards',
        shimmer: 'shimmer 2.5s linear infinite',
        blob: 'blob 15s infinite ease-in-out',
        blob2: 'blob2 18s infinite ease-in-out',
        blob3: 'blob3 20s infinite ease-in-out',
      }
    },
  },
  plugins: [],
  darkMode: 'class', //Enable class-based dark mode
}

